from __future__ import annotations

import argparse
import getpass
import os
import platform
import shutil
import socket
import subprocess
import sys
from importlib.resources import files as resource_files
from pathlib import Path
from typing import Iterable

APP_NAME = "tailscale-userspace-proxy"
DEFAULT_HOME = Path(os.environ.get("TAILSCALE_PROXY_HOME", Path.home() / f".{APP_NAME}")).expanduser()
REPO_URL = "https://github.com/cadugevaerd/tailscale-userspace-proxy"
RAW_MAIN = "https://raw.githubusercontent.com/cadugevaerd/tailscale-userspace-proxy/main"


class CliError(RuntimeError):
    pass


def info(message: str) -> None:
    print(message)


def warn(message: str) -> None:
    print(f"⚠️  {message}")


def ok(message: str) -> None:
    print(f"✅ {message}")


def fail(message: str) -> None:
    print(f"❌ {message}", file=sys.stderr)


def app_home(args: argparse.Namespace | None = None) -> Path:
    value = getattr(args, "home", None) if args else None
    return Path(value).expanduser() if value else DEFAULT_HOME


def compose_path(home: Path) -> Path:
    return home / "compose.yaml"


def env_path(home: Path) -> Path:
    return home / ".env"


def run(cmd: list[str], cwd: Path | None = None, check: bool = True, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=str(cwd) if cwd else None, text=True, capture_output=True, check=check, env=env)


def stream(cmd: list[str], cwd: Path | None = None, check: bool = True) -> int:
    proc = subprocess.run(cmd, cwd=str(cwd) if cwd else None, text=True)
    if check and proc.returncode != 0:
        raise CliError(f"Command failed with exit code {proc.returncode}: {' '.join(cmd)}")
    return proc.returncode


def which(name: str) -> str | None:
    return shutil.which(name)


def command_exists(name: str) -> bool:
    return which(name) is not None


def docker_compose_cmd() -> list[str] | None:
    if not command_exists("docker"):
        return None
    proc = run(["docker", "compose", "version"], check=False)
    if proc.returncode == 0:
        return ["docker", "compose"]
    if command_exists("docker-compose"):
        proc = run(["docker-compose", "version"], check=False)
        if proc.returncode == 0:
            return ["docker-compose"]
    return None


def compose_cmd(home: Path) -> list[str]:
    cmd = docker_compose_cmd()
    if cmd is None:
        raise CliError("Docker Compose v2 was not found. Install Docker Desktop or Docker Engine with the compose plugin.")
    return [*cmd, "--env-file", str(env_path(home)), "-f", str(compose_path(home))]


def load_template() -> str:
    return resource_files("tailscale_proxy").joinpath("templates/compose.yaml").read_text()


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def write_env(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by tailscale-proxy. Do not commit this file.",
        "# Recommended Tailscale key: reusable + ephemeral + pre-approved/tagged when possible.",
    ]
    for key in [
        "TS_AUTHKEY",
        "TS_HOSTNAME",
        "PROXY_PORT",
        "PROXY_BIND",
        "TS_ACCEPT_DNS",
        "TS_EXTRA_ARGS",
        "TAILSCALE_IMAGE",
        "CONTAINER_NAME",
    ]:
        lines.append(f"{key}={values.get(key, '')}")
    path.write_text("\n".join(lines) + "\n")
    try:
        path.chmod(0o600)
    except PermissionError:
        warn(f"Could not chmod 600 {path}. Please restrict permissions manually.")


def ensure_project_files(home: Path, force: bool = False) -> None:
    home.mkdir(parents=True, exist_ok=True)
    cpath = compose_path(home)
    if force or not cpath.exists():
        cpath.write_text(load_template())
    gitignore = home / ".gitignore"
    if force or not gitignore.exists():
        gitignore.write_text(".env\n")


def prompt_value(label: str, default: str | None = None, secret: bool = False) -> str:
    suffix = f" [{default}]" if default is not None else ""
    prompt = f"{label}{suffix}: "
    if secret:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt)
    if not value and default is not None:
        return default
    return value


def ensure_port_available(bind_addr: str, port: int) -> bool:
    host = bind_addr if bind_addr not in ("0.0.0.0", "::") else ""
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        sock.bind((host, port))
        return True
    except OSError:
        return False
    finally:
        sock.close()


def check_docker_daemon() -> tuple[bool, str]:
    if not command_exists("docker"):
        return False, "docker command not found"
    proc = run(["docker", "info"], check=False)
    if proc.returncode != 0:
        return False, (proc.stderr or proc.stdout or "docker daemon not reachable").strip()
    return True, "Docker daemon reachable"


def maybe_install_docker(args: argparse.Namespace) -> None:
    if not getattr(args, "install_docker", False):
        return
    system = platform.system().lower()
    if system not in {"linux"}:
        raise CliError("Automatic Docker install is only supported on Linux. Install Docker Desktop manually on macOS/Windows.")
    if not command_exists("curl"):
        raise CliError("curl is required for automatic Docker installation.")
    if not getattr(args, "yes", False):
        warn("This will run Docker's official convenience installer: https://get.docker.com")
        answer = input("Continue? [y/N]: ").strip().lower()
        if answer not in {"y", "yes"}:
            raise CliError("Docker installation cancelled.")
    cmd = "curl -fsSL https://get.docker.com | sh"
    if os.geteuid() != 0 and command_exists("sudo"):
        cmd = f"curl -fsSL https://get.docker.com | sudo sh"
    info("🐳 Installing Docker Engine...")
    rc = subprocess.run(cmd, shell=True).returncode
    if rc != 0:
        raise CliError("Docker installer failed. Install Docker manually and run tailscale-proxy install again.")


def cmd_install(args: argparse.Namespace) -> int:
    home = app_home(args)
    info("🔍 Checking prerequisites...")
    if sys.version_info < (3, 10):
        raise CliError("Python >= 3.10 is required.")
    ok(f"Python {platform.python_version()}")

    if command_exists("uv"):
        proc = run(["uv", "--version"], check=False)
        ok((proc.stdout or "uv found").strip())
    else:
        warn("uv not found. The bootstrap installer can install uv automatically; this CLI can still run if already installed.")

    docker_ok, docker_message = check_docker_daemon()
    if not docker_ok:
        warn(docker_message)
        maybe_install_docker(args)
        docker_ok, docker_message = check_docker_daemon()
    if not docker_ok:
        raise CliError("Docker is required and not ready. Start Docker Desktop/daemon and retry.")
    ok(docker_message)

    if docker_compose_cmd() is None:
        raise CliError("Docker Compose v2 is required.")
    ok("Docker Compose found")

    ensure_project_files(home, force=args.force)
    current = parse_env_file(env_path(home))

    auth_key = args.auth_key or current.get("TS_AUTHKEY") or os.environ.get("TS_AUTHKEY")
    non_interactive = args.non_interactive
    if not auth_key and not non_interactive:
        auth_key = prompt_value("Tailscale auth key", secret=True)
    if not auth_key:
        raise CliError("TS_AUTHKEY is required. Create an ephemeral auth key in Tailscale admin and rerun install.")

    hostname = args.hostname or current.get("TS_HOSTNAME") or "tailscale-userspace-proxy"
    port = str(args.port or current.get("PROXY_PORT") or "1055")
    bind_addr = args.bind or current.get("PROXY_BIND") or "127.0.0.1"
    accept_dns = str(args.accept_dns if args.accept_dns is not None else current.get("TS_ACCEPT_DNS") or "true").lower()
    extra_args = args.extra_args if args.extra_args is not None else current.get("TS_EXTRA_ARGS", "")

    if not non_interactive:
        hostname = prompt_value("Tailscale hostname", hostname)
        port = prompt_value("Proxy port", port)
        bind_addr = prompt_value("Bind address", bind_addr)
        accept_dns = prompt_value("Accept Tailscale DNS", accept_dns)
        if not extra_args:
            extra_args = prompt_value("Extra tailscale up args", "")

    try:
        port_int = int(port)
    except ValueError as exc:
        raise CliError("Proxy port must be a number.") from exc

    if bind_addr == "0.0.0.0":
        warn("PROXY_BIND=0.0.0.0 exposes the proxy to the network. Do not expose it to the public internet.")
    if not ensure_port_available(bind_addr, port_int):
        warn(f"Port {bind_addr}:{port_int} looks busy. Continuing because Docker may already own it from this stack.")

    values = {
        "TS_AUTHKEY": auth_key,
        "TS_HOSTNAME": hostname,
        "PROXY_PORT": str(port_int),
        "PROXY_BIND": bind_addr,
        "TS_ACCEPT_DNS": accept_dns,
        "TS_EXTRA_ARGS": extra_args,
        "TAILSCALE_IMAGE": current.get("TAILSCALE_IMAGE", "tailscale/tailscale:stable"),
        "CONTAINER_NAME": current.get("CONTAINER_NAME", "tailscale-userspace-proxy"),
    }
    write_env(env_path(home), values)
    ok(f"Config written to {home}")
    info("\nNext command:")
    info("  tailscale-proxy up")
    return 0


def ensure_installed(home: Path) -> None:
    if not compose_path(home).exists() or not env_path(home).exists():
        raise CliError("Not installed yet. Run: tailscale-proxy install  (or tailscale-proxy up --init)")


def cmd_up(args: argparse.Namespace) -> int:
    home = app_home(args)
    if args.init and (not compose_path(home).exists() or not env_path(home).exists()):
        cmd_install(args)
    ensure_installed(home)
    info("🚀 Starting Tailscale userspace proxy...")
    stream([*compose_cmd(home), "up", "-d"], cwd=home)
    ok("Proxy stack started")
    return cmd_status(args)


def cmd_down(args: argparse.Namespace) -> int:
    home = app_home(args)
    ensure_installed(home)
    stream([*compose_cmd(home), "down"], cwd=home)
    ok("Proxy stack stopped")
    return 0


def cmd_restart(args: argparse.Namespace) -> int:
    cmd_down(args)
    return cmd_up(args)


def cmd_status(args: argparse.Namespace) -> int:
    home = app_home(args)
    ensure_installed(home)
    info("📦 Docker Compose status:")
    stream([*compose_cmd(home), "ps"], cwd=home, check=False)
    info("\n🌐 Tailscale status:")
    stream([*compose_cmd(home), "exec", "-T", "tailscale-proxy", "tailscale", "status", "--peers=false"], cwd=home, check=False)
    cfg = parse_env_file(env_path(home))
    bind = cfg.get("PROXY_BIND", "127.0.0.1")
    port = cfg.get("PROXY_PORT", "1055")
    info("\nProxy URLs:")
    info(f"  SOCKS5: socks5h://{bind}:{port}")
    info(f"  HTTP:   http://{bind}:{port}")
    return 0


def cmd_logs(args: argparse.Namespace) -> int:
    home = app_home(args)
    ensure_installed(home)
    cmd = [*compose_cmd(home), "logs", "--tail", str(args.tail)]
    if args.follow:
        cmd.append("-f")
    return stream(cmd, cwd=home, check=False)


def cmd_test(args: argparse.Namespace) -> int:
    home = app_home(args)
    ensure_installed(home)
    if not command_exists("curl"):
        raise CliError("curl is required for the smoke test.")
    cfg = parse_env_file(env_path(home))
    bind = cfg.get("PROXY_BIND", "127.0.0.1")
    if bind == "0.0.0.0":
        bind = "127.0.0.1"
    port = cfg.get("PROXY_PORT", "1055")
    target = args.target
    proxy = f"socks5h://{bind}:{port}"
    info(f"🧪 Testing via {proxy} -> {target}")
    return stream(["curl", "--fail", "--show-error", "--location", "--max-time", str(args.timeout), "--proxy", proxy, target], check=False)


def cmd_config(args: argparse.Namespace) -> int:
    home = app_home(args)
    ensure_project_files(home, force=False)
    info(f"Home:        {home}")
    info(f"Compose:     {compose_path(home)}")
    info(f"Environment: {env_path(home)}")
    cfg = parse_env_file(env_path(home))
    if cfg:
        info("\nCurrent config:")
        for key in sorted(cfg):
            value = "***" if key == "TS_AUTHKEY" and cfg[key] else cfg[key]
            info(f"  {key}={value}")
    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    home = app_home(args)
    if not compose_path(home).exists():
        ensure_project_files(home, force=False)
    if not env_path(home).exists():
        write_env(env_path(home), {
            "TS_AUTHKEY": "tskey-auth-test-do-not-use",
            "TS_HOSTNAME": "tailscale-userspace-proxy",
            "PROXY_PORT": "1055",
            "PROXY_BIND": "127.0.0.1",
            "TS_ACCEPT_DNS": "true",
            "TS_EXTRA_ARGS": "",
            "TAILSCALE_IMAGE": "tailscale/tailscale:stable",
            "CONTAINER_NAME": "tailscale-userspace-proxy",
        })
    if docker_compose_cmd() is None:
        warn("Docker Compose not found; validating files only.")
        ok("Project files exist")
        return 0
    proc = run([*compose_cmd(home), "config"], cwd=home, check=False)
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr, file=sys.stderr)
        raise CliError("docker compose config failed")
    ok("docker compose config passed")
    return 0


def cmd_update(args: argparse.Namespace) -> int:
    if command_exists("uv"):
        info("⬆️  Updating uv tool from GitHub...")
        return stream(["uv", "tool", "install", "--force", f"git+{REPO_URL}"], check=False)
    raise CliError("uv not found. Reinstall with the bootstrap command from the README.")


def cmd_uninstall(args: argparse.Namespace) -> int:
    home = app_home(args)
    if compose_path(home).exists() and env_path(home).exists():
        stream([*compose_cmd(home), "down", "-v"], cwd=home, check=False)
    if args.keep_config:
        ok(f"Containers removed. Config kept at {home}")
        return 0
    if home.exists():
        if not args.yes:
            answer = input(f"Delete {home}? [y/N]: ").strip().lower()
            if answer not in {"y", "yes"}:
                ok(f"Config kept at {home}")
                return 0
        shutil.rmtree(home)
    ok("Uninstalled")
    return 0


def add_common(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--home", default=None, help=f"Config directory (default: {DEFAULT_HOME})")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="tailscale-proxy", description="Manage a Tailscale userspace SOCKS5/HTTP proxy with Docker Compose.")
    parser.add_argument("--version", action="version", version="tailscale-proxy 0.1.0")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("install", help="Create config, validate prerequisites, and prepare the Docker Compose stack.")
    add_common(p)
    p.add_argument("--auth-key", default=None, help="Tailscale auth key. Prefer prompt/env over shell history.")
    p.add_argument("--hostname", default=None, help="Tailscale node hostname.")
    p.add_argument("--port", type=int, default=None, help="Host proxy port. Default: 1055")
    p.add_argument("--bind", default=None, help="Host bind address. Default: 127.0.0.1")
    p.add_argument("--accept-dns", choices=["true", "false"], default=None, help="Accept Tailscale DNS/MagicDNS.")
    p.add_argument("--extra-args", default=None, help="Extra args passed to tailscale up via TS_EXTRA_ARGS.")
    p.add_argument("--install-docker", action="store_true", help="Attempt Docker install on Linux if missing.")
    p.add_argument("--yes", action="store_true", help="Assume yes for destructive/installer prompts.")
    p.add_argument("--force", action="store_true", help="Overwrite generated compose/config helper files.")
    p.add_argument("--non-interactive", action="store_true", help="Do not prompt; require flags/env/defaults.")
    p.set_defaults(func=cmd_install)

    p = sub.add_parser("up", help="Start the proxy stack.")
    add_common(p)
    p.add_argument("--init", action="store_true", help="Run install first if config is missing.")
    p.add_argument("--auth-key", default=None, help=argparse.SUPPRESS)
    p.add_argument("--hostname", default=None, help=argparse.SUPPRESS)
    p.add_argument("--port", type=int, default=None, help=argparse.SUPPRESS)
    p.add_argument("--bind", default=None, help=argparse.SUPPRESS)
    p.add_argument("--accept-dns", choices=["true", "false"], default=None, help=argparse.SUPPRESS)
    p.add_argument("--extra-args", default=None, help=argparse.SUPPRESS)
    p.add_argument("--install-docker", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--yes", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--force", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--non-interactive", action="store_true", help=argparse.SUPPRESS)
    p.set_defaults(func=cmd_up)

    for name, help_text, func in [
        ("down", "Stop and remove the proxy container.", cmd_down),
        ("restart", "Restart the proxy stack.", cmd_restart),
        ("status", "Show Docker and Tailscale status.", cmd_status),
        ("config", "Show config paths and values without revealing the auth key.", cmd_config),
        ("validate", "Validate generated files and docker compose config.", cmd_validate),
    ]:
        p = sub.add_parser(name, help=help_text)
        add_common(p)
        p.set_defaults(func=func)

    p = sub.add_parser("logs", help="Show container logs.")
    add_common(p)
    p.add_argument("-f", "--follow", action="store_true")
    p.add_argument("--tail", type=int, default=100)
    p.set_defaults(func=cmd_logs)

    p = sub.add_parser("test", help="Smoke test a URL through the SOCKS5 proxy.")
    add_common(p)
    p.add_argument("target", nargs="?", default="https://ifconfig.me", help="URL to fetch via proxy.")
    p.add_argument("--timeout", type=int, default=20)
    p.set_defaults(func=cmd_test)

    p = sub.add_parser("update", help="Update the installed uv tool from GitHub.")
    add_common(p)
    p.set_defaults(func=cmd_update)

    p = sub.add_parser("uninstall", help="Stop stack and remove local config.")
    add_common(p)
    p.add_argument("--keep-config", action="store_true")
    p.add_argument("--yes", action="store_true")
    p.set_defaults(func=cmd_uninstall)

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    try:
        return int(args.func(args) or 0)
    except KeyboardInterrupt:
        fail("Interrupted")
        return 130
    except CliError as exc:
        fail(str(exc))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
